# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 514c42e9598b616b26bf5a523a34686d56672b4ad0d4c27cdb286edf7e29e5e292f700b0dcc7634fb7eb1ed00e3c3d03e273a6d46610eb15dd7f44c649f42174

test:
  secret_key_base: 0d30f5eb3b59d37d740dd083b3161cb7694770bd20316eb56b44359528b27e55d7e71b6fcc975d77570f6249c38f5902f753f70e4ac4d0b9e4bce860f8d4d7ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
